#ifndef CORE_HEADER_SDL_EVENT_GUARD
#define CORE_HEADER_SDL_EVENT_GUARD

#include <SDL3/SDL.h>
#include <array>
#include <unordered_map>
#include <string_view>
#include <string>

namespace{

	bool start_with(const char* str, const char* prefix) {
		return std::string_view(str).starts_with(prefix);
	}

	inline static const auto &get_event_type_table() noexcept{
		static const std::array event_type_arr = {
			std::pair{SDL_EVENT_FIRST,"SDL_EVENT_FIRST"},
			std::pair{SDL_EVENT_QUIT,"SDL_EVENT_QUIT"},
			std::pair{SDL_EVENT_TERMINATING,"SDL_EVENT_TERMINATING"},
			std::pair{SDL_EVENT_LOW_MEMORY,"SDL_EVENT_LOW_MEMORY"},
			std::pair{SDL_EVENT_WILL_ENTER_BACKGROUND,"SDL_EVENT_WILL_ENTER_BACKGROUND"},
			std::pair{SDL_EVENT_DID_ENTER_BACKGROUND,"SDL_EVENT_DID_ENTER_BACKGROUND"},
			std::pair{SDL_EVENT_WILL_ENTER_FOREGROUND,"SDL_EVENT_WILL_ENTER_FOREGROUND"},
			std::pair{SDL_EVENT_DID_ENTER_FOREGROUND,"SDL_EVENT_DID_ENTER_FOREGROUND"},
			std::pair{SDL_EVENT_LOCALE_CHANGED,"SDL_EVENT_LOCALE_CHANGED"},
			std::pair{SDL_EVENT_SYSTEM_THEME_CHANGED,"SDL_EVENT_SYSTEM_THEME_CHANGED"},
			std::pair{SDL_EVENT_DISPLAY_ORIENTATION,"SDL_EVENT_DISPLAY_ORIENTATION"},
			std::pair{SDL_EVENT_DISPLAY_ADDED,"SDL_EVENT_DISPLAY_ADDED"},
			std::pair{SDL_EVENT_DISPLAY_REMOVED,"SDL_EVENT_DISPLAY_REMOVED"},
			std::pair{SDL_EVENT_DISPLAY_MOVED,"SDL_EVENT_DISPLAY_MOVED"},
			std::pair{SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED,"SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED"},
			std::pair{SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED,"SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED"},
			std::pair{SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED,"SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED"},
			std::pair{SDL_EVENT_DISPLAY_USABLE_BOUNDS_CHANGED,"SDL_EVENT_DISPLAY_USABLE_BOUNDS_CHANGED"},
			std::pair{SDL_EVENT_DISPLAY_FIRST,"SDL_EVENT_DISPLAY_FIRST"},
			std::pair{SDL_EVENT_DISPLAY_LAST,"SDL_EVENT_DISPLAY_LAST"},
			std::pair{SDL_EVENT_WINDOW_SHOWN,"SDL_EVENT_WINDOW_SHOWN"},
			std::pair{SDL_EVENT_WINDOW_HIDDEN,"SDL_EVENT_WINDOW_HIDDEN"},
			std::pair{SDL_EVENT_WINDOW_EXPOSED,"SDL_EVENT_WINDOW_EXPOSED"},
			std::pair{SDL_EVENT_WINDOW_MOVED,"SDL_EVENT_WINDOW_MOVED"},
			std::pair{SDL_EVENT_WINDOW_RESIZED,"SDL_EVENT_WINDOW_RESIZED"},
			std::pair{SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED,"SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED"},
			std::pair{SDL_EVENT_WINDOW_METAL_VIEW_RESIZED,"SDL_EVENT_WINDOW_METAL_VIEW_RESIZED"},
			std::pair{SDL_EVENT_WINDOW_MINIMIZED,"SDL_EVENT_WINDOW_MINIMIZED"},
			std::pair{SDL_EVENT_WINDOW_MAXIMIZED,"SDL_EVENT_WINDOW_MAXIMIZED"},
			std::pair{SDL_EVENT_WINDOW_RESTORED,"SDL_EVENT_WINDOW_RESTORED"},
			std::pair{SDL_EVENT_WINDOW_MOUSE_ENTER,"SDL_EVENT_WINDOW_MOUSE_ENTER"},
			std::pair{SDL_EVENT_WINDOW_MOUSE_LEAVE,"SDL_EVENT_WINDOW_MOUSE_LEAVE"},
			std::pair{SDL_EVENT_WINDOW_FOCUS_GAINED,"SDL_EVENT_WINDOW_FOCUS_GAINED"},
			std::pair{SDL_EVENT_WINDOW_FOCUS_LOST,"SDL_EVENT_WINDOW_FOCUS_LOST"},
			std::pair{SDL_EVENT_WINDOW_CLOSE_REQUESTED,"SDL_EVENT_WINDOW_CLOSE_REQUESTED"},
			std::pair{SDL_EVENT_WINDOW_HIT_TEST,"SDL_EVENT_WINDOW_HIT_TEST"},
			std::pair{SDL_EVENT_WINDOW_ICCPROF_CHANGED,"SDL_EVENT_WINDOW_ICCPROF_CHANGED"},
			std::pair{SDL_EVENT_WINDOW_DISPLAY_CHANGED,"SDL_EVENT_WINDOW_DISPLAY_CHANGED"},
			std::pair{SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED,"SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED"},
			std::pair{SDL_EVENT_WINDOW_SAFE_AREA_CHANGED,"SDL_EVENT_WINDOW_SAFE_AREA_CHANGED"},
			std::pair{SDL_EVENT_WINDOW_OCCLUDED,"SDL_EVENT_WINDOW_OCCLUDED"},
			std::pair{SDL_EVENT_WINDOW_ENTER_FULLSCREEN,"SDL_EVENT_WINDOW_ENTER_FULLSCREEN"},
			std::pair{SDL_EVENT_WINDOW_LEAVE_FULLSCREEN,"SDL_EVENT_WINDOW_LEAVE_FULLSCREEN"},
			std::pair{SDL_EVENT_WINDOW_DESTROYED,"SDL_EVENT_WINDOW_DESTROYED"},
			std::pair{SDL_EVENT_WINDOW_HDR_STATE_CHANGED,"SDL_EVENT_WINDOW_HDR_STATE_CHANGED"},
			std::pair{SDL_EVENT_WINDOW_FIRST,"SDL_EVENT_WINDOW_FIRST"},
			std::pair{SDL_EVENT_WINDOW_LAST,"SDL_EVENT_WINDOW_LAST"},
			std::pair{SDL_EVENT_KEY_DOWN,"SDL_EVENT_KEY_DOWN"},
			std::pair{SDL_EVENT_KEY_UP,"SDL_EVENT_KEY_UP"},
			std::pair{SDL_EVENT_TEXT_EDITING,"SDL_EVENT_TEXT_EDITING"},
			std::pair{SDL_EVENT_TEXT_INPUT,"SDL_EVENT_TEXT_INPUT"},
			std::pair{SDL_EVENT_KEYMAP_CHANGED,"SDL_EVENT_KEYMAP_CHANGED"},
			std::pair{SDL_EVENT_KEYBOARD_ADDED,"SDL_EVENT_KEYBOARD_ADDED"},
			std::pair{SDL_EVENT_KEYBOARD_REMOVED,"SDL_EVENT_KEYBOARD_REMOVED"},
			std::pair{SDL_EVENT_TEXT_EDITING_CANDIDATES,"SDL_EVENT_TEXT_EDITING_CANDIDATES"},
			std::pair{SDL_EVENT_SCREEN_KEYBOARD_SHOWN,"SDL_EVENT_SCREEN_KEYBOARD_SHOWN"},
			std::pair{SDL_EVENT_SCREEN_KEYBOARD_HIDDEN,"SDL_EVENT_SCREEN_KEYBOARD_HIDDEN"},
			std::pair{SDL_EVENT_MOUSE_MOTION,"SDL_EVENT_MOUSE_MOTION"},
			std::pair{SDL_EVENT_MOUSE_BUTTON_DOWN,"SDL_EVENT_MOUSE_BUTTON_DOWN"},
			std::pair{SDL_EVENT_MOUSE_BUTTON_UP,"SDL_EVENT_MOUSE_BUTTON_UP"},
			std::pair{SDL_EVENT_MOUSE_WHEEL,"SDL_EVENT_MOUSE_WHEEL"},
			std::pair{SDL_EVENT_MOUSE_ADDED,"SDL_EVENT_MOUSE_ADDED"},
			std::pair{SDL_EVENT_MOUSE_REMOVED,"SDL_EVENT_MOUSE_REMOVED"},
			std::pair{SDL_EVENT_JOYSTICK_AXIS_MOTION,"SDL_EVENT_JOYSTICK_AXIS_MOTION"},
			std::pair{SDL_EVENT_JOYSTICK_BALL_MOTION,"SDL_EVENT_JOYSTICK_BALL_MOTION"},
			std::pair{SDL_EVENT_JOYSTICK_HAT_MOTION,"SDL_EVENT_JOYSTICK_HAT_MOTION"},
			std::pair{SDL_EVENT_JOYSTICK_BUTTON_DOWN,"SDL_EVENT_JOYSTICK_BUTTON_DOWN"},
			std::pair{SDL_EVENT_JOYSTICK_BUTTON_UP,"SDL_EVENT_JOYSTICK_BUTTON_UP"},
			std::pair{SDL_EVENT_JOYSTICK_ADDED,"SDL_EVENT_JOYSTICK_ADDED"},
			std::pair{SDL_EVENT_JOYSTICK_REMOVED,"SDL_EVENT_JOYSTICK_REMOVED"},
			std::pair{SDL_EVENT_JOYSTICK_BATTERY_UPDATED,"SDL_EVENT_JOYSTICK_BATTERY_UPDATED"},
			std::pair{SDL_EVENT_JOYSTICK_UPDATE_COMPLETE,"SDL_EVENT_JOYSTICK_UPDATE_COMPLETE"},
			std::pair{SDL_EVENT_GAMEPAD_AXIS_MOTION,"SDL_EVENT_GAMEPAD_AXIS_MOTION"},
			std::pair{SDL_EVENT_GAMEPAD_BUTTON_DOWN,"SDL_EVENT_GAMEPAD_BUTTON_DOWN"},
			std::pair{SDL_EVENT_GAMEPAD_BUTTON_UP,"SDL_EVENT_GAMEPAD_BUTTON_UP"},
			std::pair{SDL_EVENT_GAMEPAD_ADDED,"SDL_EVENT_GAMEPAD_ADDED"},
			std::pair{SDL_EVENT_GAMEPAD_REMOVED,"SDL_EVENT_GAMEPAD_REMOVED"},
			std::pair{SDL_EVENT_GAMEPAD_REMAPPED,"SDL_EVENT_GAMEPAD_REMAPPED"},
			std::pair{SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN,"SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN"},
			std::pair{SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION,"SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION"},
			std::pair{SDL_EVENT_GAMEPAD_TOUCHPAD_UP,"SDL_EVENT_GAMEPAD_TOUCHPAD_UP"},
			std::pair{SDL_EVENT_GAMEPAD_SENSOR_UPDATE,"SDL_EVENT_GAMEPAD_SENSOR_UPDATE"},
			std::pair{SDL_EVENT_GAMEPAD_UPDATE_COMPLETE,"SDL_EVENT_GAMEPAD_UPDATE_COMPLETE"},
			std::pair{SDL_EVENT_GAMEPAD_STEAM_HANDLE_UPDATED,"SDL_EVENT_GAMEPAD_STEAM_HANDLE_UPDATED"},
			std::pair{SDL_EVENT_FINGER_DOWN,"SDL_EVENT_FINGER_DOWN"},
			std::pair{SDL_EVENT_FINGER_UP,"SDL_EVENT_FINGER_UP"},
			std::pair{SDL_EVENT_FINGER_MOTION,"SDL_EVENT_FINGER_MOTION"},
			std::pair{SDL_EVENT_FINGER_CANCELED,"SDL_EVENT_FINGER_CANCELED"},
			std::pair{SDL_EVENT_PINCH_BEGIN,"SDL_EVENT_PINCH_BEGIN"},
			std::pair{SDL_EVENT_PINCH_UPDATE,"SDL_EVENT_PINCH_UPDATE"},
			std::pair{SDL_EVENT_PINCH_END,"SDL_EVENT_PINCH_END"},
			std::pair{SDL_EVENT_CLIPBOARD_UPDATE,"SDL_EVENT_CLIPBOARD_UPDATE"},
			std::pair{SDL_EVENT_DROP_FILE,"SDL_EVENT_DROP_FILE"},
			std::pair{SDL_EVENT_DROP_TEXT,"SDL_EVENT_DROP_TEXT"},
			std::pair{SDL_EVENT_DROP_BEGIN,"SDL_EVENT_DROP_BEGIN"},
			std::pair{SDL_EVENT_DROP_COMPLETE,"SDL_EVENT_DROP_COMPLETE"},
			std::pair{SDL_EVENT_DROP_POSITION,"SDL_EVENT_DROP_POSITION"},
			std::pair{SDL_EVENT_AUDIO_DEVICE_ADDED,"SDL_EVENT_AUDIO_DEVICE_ADDED"},
			std::pair{SDL_EVENT_AUDIO_DEVICE_REMOVED,"SDL_EVENT_AUDIO_DEVICE_REMOVED"},
			std::pair{SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED,"SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED"},
			std::pair{SDL_EVENT_SENSOR_UPDATE,"SDL_EVENT_SENSOR_UPDATE"},
			std::pair{SDL_EVENT_PEN_PROXIMITY_IN,"SDL_EVENT_PEN_PROXIMITY_IN"},
			std::pair{SDL_EVENT_PEN_PROXIMITY_OUT,"SDL_EVENT_PEN_PROXIMITY_OUT"},
			std::pair{SDL_EVENT_PEN_DOWN,"SDL_EVENT_PEN_DOWN"},
			std::pair{SDL_EVENT_PEN_UP,"SDL_EVENT_PEN_UP"},
			std::pair{SDL_EVENT_PEN_BUTTON_DOWN,"SDL_EVENT_PEN_BUTTON_DOWN"},
			std::pair{SDL_EVENT_PEN_BUTTON_UP,"SDL_EVENT_PEN_BUTTON_UP"},
			std::pair{SDL_EVENT_PEN_MOTION,"SDL_EVENT_PEN_MOTION"},
			std::pair{SDL_EVENT_PEN_AXIS,"SDL_EVENT_PEN_AXIS"},
			std::pair{SDL_EVENT_CAMERA_DEVICE_ADDED,"SDL_EVENT_CAMERA_DEVICE_ADDED"},
			std::pair{SDL_EVENT_CAMERA_DEVICE_REMOVED,"SDL_EVENT_CAMERA_DEVICE_REMOVED"},
			std::pair{SDL_EVENT_CAMERA_DEVICE_APPROVED,"SDL_EVENT_CAMERA_DEVICE_APPROVED"},
			std::pair{SDL_EVENT_CAMERA_DEVICE_DENIED,"SDL_EVENT_CAMERA_DEVICE_DENIED"},
			std::pair{SDL_EVENT_RENDER_TARGETS_RESET,"SDL_EVENT_RENDER_TARGETS_RESET"},
			std::pair{SDL_EVENT_RENDER_DEVICE_RESET,"SDL_EVENT_RENDER_DEVICE_RESET"},
			std::pair{SDL_EVENT_RENDER_DEVICE_LOST,"SDL_EVENT_RENDER_DEVICE_LOST"},
			std::pair{SDL_EVENT_PRIVATE0,"SDL_EVENT_PRIVATE0"},
			std::pair{SDL_EVENT_PRIVATE1,"SDL_EVENT_PRIVATE1"},
			std::pair{SDL_EVENT_PRIVATE2,"SDL_EVENT_PRIVATE2"},
			std::pair{SDL_EVENT_PRIVATE3,"SDL_EVENT_PRIVATE3"},
			std::pair{SDL_EVENT_POLL_SENTINEL,"SDL_EVENT_POLL_SENTINEL"},
			std::pair{SDL_EVENT_USER,"SDL_EVENT_USER"},
			std::pair{SDL_EVENT_LAST,"SDL_EVENT_LAST"},
			std::pair{SDL_EVENT_ENUM_PADDING,"SDL_EVENT_ENUM_PADDING"}
		};

		return event_type_arr;
	}

	inline static const auto &get_scancode_table() noexcept{
		static const std::array scancode_arr = {
			std::pair{SDL_SCANCODE_UNKNOWN,"SDL_SCANCODE_UNKNOWN"},
			std::pair{SDL_SCANCODE_A,"SDL_SCANCODE_A"},
			std::pair{SDL_SCANCODE_B,"SDL_SCANCODE_B"},
			std::pair{SDL_SCANCODE_C,"SDL_SCANCODE_C"},
			std::pair{SDL_SCANCODE_D,"SDL_SCANCODE_D"},
			std::pair{SDL_SCANCODE_E,"SDL_SCANCODE_E"},
			std::pair{SDL_SCANCODE_F,"SDL_SCANCODE_F"},
			std::pair{SDL_SCANCODE_G,"SDL_SCANCODE_G"},
			std::pair{SDL_SCANCODE_H,"SDL_SCANCODE_H"},
			std::pair{SDL_SCANCODE_I,"SDL_SCANCODE_I"},
			std::pair{SDL_SCANCODE_J,"SDL_SCANCODE_J"},
			std::pair{SDL_SCANCODE_K,"SDL_SCANCODE_K"},
			std::pair{SDL_SCANCODE_L,"SDL_SCANCODE_L"},
			std::pair{SDL_SCANCODE_M,"SDL_SCANCODE_M"},
			std::pair{SDL_SCANCODE_N,"SDL_SCANCODE_N"},
			std::pair{SDL_SCANCODE_O,"SDL_SCANCODE_O"},
			std::pair{SDL_SCANCODE_P,"SDL_SCANCODE_P"},
			std::pair{SDL_SCANCODE_Q,"SDL_SCANCODE_Q"},
			std::pair{SDL_SCANCODE_R,"SDL_SCANCODE_R"},
			std::pair{SDL_SCANCODE_S,"SDL_SCANCODE_S"},
			std::pair{SDL_SCANCODE_T,"SDL_SCANCODE_T"},
			std::pair{SDL_SCANCODE_U,"SDL_SCANCODE_U"},
			std::pair{SDL_SCANCODE_V,"SDL_SCANCODE_V"},
			std::pair{SDL_SCANCODE_W,"SDL_SCANCODE_W"},
			std::pair{SDL_SCANCODE_X,"SDL_SCANCODE_X"},
			std::pair{SDL_SCANCODE_Y,"SDL_SCANCODE_Y"},
			std::pair{SDL_SCANCODE_Z,"SDL_SCANCODE_Z"},
			std::pair{SDL_SCANCODE_1,"SDL_SCANCODE_1"},
			std::pair{SDL_SCANCODE_2,"SDL_SCANCODE_2"},
			std::pair{SDL_SCANCODE_3,"SDL_SCANCODE_3"},
			std::pair{SDL_SCANCODE_4,"SDL_SCANCODE_4"},
			std::pair{SDL_SCANCODE_5,"SDL_SCANCODE_5"},
			std::pair{SDL_SCANCODE_6,"SDL_SCANCODE_6"},
			std::pair{SDL_SCANCODE_7,"SDL_SCANCODE_7"},
			std::pair{SDL_SCANCODE_8,"SDL_SCANCODE_8"},
			std::pair{SDL_SCANCODE_9,"SDL_SCANCODE_9"},
			std::pair{SDL_SCANCODE_0,"SDL_SCANCODE_0"},
			std::pair{SDL_SCANCODE_RETURN,"SDL_SCANCODE_RETURN"},
			std::pair{SDL_SCANCODE_ESCAPE,"SDL_SCANCODE_ESCAPE"},
			std::pair{SDL_SCANCODE_BACKSPACE,"SDL_SCANCODE_BACKSPACE"},
			std::pair{SDL_SCANCODE_TAB,"SDL_SCANCODE_TAB"},
			std::pair{SDL_SCANCODE_SPACE,"SDL_SCANCODE_SPACE"},
			std::pair{SDL_SCANCODE_MINUS,"SDL_SCANCODE_MINUS"},
			std::pair{SDL_SCANCODE_EQUALS,"SDL_SCANCODE_EQUALS"},
			std::pair{SDL_SCANCODE_LEFTBRACKET,"SDL_SCANCODE_LEFTBRACKET"},
			std::pair{SDL_SCANCODE_RIGHTBRACKET,"SDL_SCANCODE_RIGHTBRACKET"},
			std::pair{SDL_SCANCODE_BACKSLASH,"SDL_SCANCODE_BACKSLASH"},
			std::pair{SDL_SCANCODE_NONUSHASH,"SDL_SCANCODE_NONUSHASH"},
			std::pair{SDL_SCANCODE_SEMICOLON,"SDL_SCANCODE_SEMICOLON"},
			std::pair{SDL_SCANCODE_APOSTROPHE,"SDL_SCANCODE_APOSTROPHE"},
			std::pair{SDL_SCANCODE_GRAVE,"SDL_SCANCODE_GRAVE"},
			std::pair{SDL_SCANCODE_COMMA,"SDL_SCANCODE_COMMA"},
			std::pair{SDL_SCANCODE_PERIOD,"SDL_SCANCODE_PERIOD"},
			std::pair{SDL_SCANCODE_SLASH,"SDL_SCANCODE_SLASH"},
			std::pair{SDL_SCANCODE_CAPSLOCK,"SDL_SCANCODE_CAPSLOCK"},
			std::pair{SDL_SCANCODE_F1,"SDL_SCANCODE_F1"},
			std::pair{SDL_SCANCODE_F2,"SDL_SCANCODE_F2"},
			std::pair{SDL_SCANCODE_F3,"SDL_SCANCODE_F3"},
			std::pair{SDL_SCANCODE_F4,"SDL_SCANCODE_F4"},
			std::pair{SDL_SCANCODE_F5,"SDL_SCANCODE_F5"},
			std::pair{SDL_SCANCODE_F6,"SDL_SCANCODE_F6"},
			std::pair{SDL_SCANCODE_F7,"SDL_SCANCODE_F7"},
			std::pair{SDL_SCANCODE_F8,"SDL_SCANCODE_F8"},
			std::pair{SDL_SCANCODE_F9,"SDL_SCANCODE_F9"},
			std::pair{SDL_SCANCODE_F10,"SDL_SCANCODE_F10"},
			std::pair{SDL_SCANCODE_F11,"SDL_SCANCODE_F11"},
			std::pair{SDL_SCANCODE_F12,"SDL_SCANCODE_F12"},
			std::pair{SDL_SCANCODE_PRINTSCREEN,"SDL_SCANCODE_PRINTSCREEN"},
			std::pair{SDL_SCANCODE_SCROLLLOCK,"SDL_SCANCODE_SCROLLLOCK"},
			std::pair{SDL_SCANCODE_PAUSE,"SDL_SCANCODE_PAUSE"},
			std::pair{SDL_SCANCODE_INSERT,"SDL_SCANCODE_INSERT"},
			std::pair{SDL_SCANCODE_HOME,"SDL_SCANCODE_HOME"},
			std::pair{SDL_SCANCODE_PAGEUP,"SDL_SCANCODE_PAGEUP"},
			std::pair{SDL_SCANCODE_DELETE,"SDL_SCANCODE_DELETE"},
			std::pair{SDL_SCANCODE_END,"SDL_SCANCODE_END"},
			std::pair{SDL_SCANCODE_PAGEDOWN,"SDL_SCANCODE_PAGEDOWN"},
			std::pair{SDL_SCANCODE_RIGHT,"SDL_SCANCODE_RIGHT"},
			std::pair{SDL_SCANCODE_LEFT,"SDL_SCANCODE_LEFT"},
			std::pair{SDL_SCANCODE_DOWN,"SDL_SCANCODE_DOWN"},
			std::pair{SDL_SCANCODE_UP,"SDL_SCANCODE_UP"},
			std::pair{SDL_SCANCODE_NUMLOCKCLEAR,"SDL_SCANCODE_NUMLOCKCLEAR"},
			std::pair{SDL_SCANCODE_KP_DIVIDE,"SDL_SCANCODE_KP_DIVIDE"},
			std::pair{SDL_SCANCODE_KP_MULTIPLY,"SDL_SCANCODE_KP_MULTIPLY"},
			std::pair{SDL_SCANCODE_KP_MINUS,"SDL_SCANCODE_KP_MINUS"},
			std::pair{SDL_SCANCODE_KP_PLUS,"SDL_SCANCODE_KP_PLUS"},
			std::pair{SDL_SCANCODE_KP_ENTER,"SDL_SCANCODE_KP_ENTER"},
			std::pair{SDL_SCANCODE_KP_1,"SDL_SCANCODE_KP_1"},
			std::pair{SDL_SCANCODE_KP_2,"SDL_SCANCODE_KP_2"},
			std::pair{SDL_SCANCODE_KP_3,"SDL_SCANCODE_KP_3"},
			std::pair{SDL_SCANCODE_KP_4,"SDL_SCANCODE_KP_4"},
			std::pair{SDL_SCANCODE_KP_5,"SDL_SCANCODE_KP_5"},
			std::pair{SDL_SCANCODE_KP_6,"SDL_SCANCODE_KP_6"},
			std::pair{SDL_SCANCODE_KP_7,"SDL_SCANCODE_KP_7"},
			std::pair{SDL_SCANCODE_KP_8,"SDL_SCANCODE_KP_8"},
			std::pair{SDL_SCANCODE_KP_9,"SDL_SCANCODE_KP_9"},
			std::pair{SDL_SCANCODE_KP_0,"SDL_SCANCODE_KP_0"},
			std::pair{SDL_SCANCODE_KP_PERIOD,"SDL_SCANCODE_KP_PERIOD"},
			std::pair{SDL_SCANCODE_NONUSBACKSLASH,"SDL_SCANCODE_NONUSBACKSLASH"},
			std::pair{SDL_SCANCODE_APPLICATION,"SDL_SCANCODE_APPLICATION"},
			std::pair{SDL_SCANCODE_POWER,"SDL_SCANCODE_POWER"},
			std::pair{SDL_SCANCODE_KP_EQUALS,"SDL_SCANCODE_KP_EQUALS"},
			std::pair{SDL_SCANCODE_F13,"SDL_SCANCODE_F13"},
			std::pair{SDL_SCANCODE_F14,"SDL_SCANCODE_F14"},
			std::pair{SDL_SCANCODE_F15,"SDL_SCANCODE_F15"},
			std::pair{SDL_SCANCODE_F16,"SDL_SCANCODE_F16"},
			std::pair{SDL_SCANCODE_F17,"SDL_SCANCODE_F17"},
			std::pair{SDL_SCANCODE_F18,"SDL_SCANCODE_F18"},
			std::pair{SDL_SCANCODE_F19,"SDL_SCANCODE_F19"},
			std::pair{SDL_SCANCODE_F20,"SDL_SCANCODE_F20"},
			std::pair{SDL_SCANCODE_F21,"SDL_SCANCODE_F21"},
			std::pair{SDL_SCANCODE_F22,"SDL_SCANCODE_F22"},
			std::pair{SDL_SCANCODE_F23,"SDL_SCANCODE_F23"},
			std::pair{SDL_SCANCODE_F24,"SDL_SCANCODE_F24"},
			std::pair{SDL_SCANCODE_EXECUTE,"SDL_SCANCODE_EXECUTE"},
			std::pair{SDL_SCANCODE_HELP,"SDL_SCANCODE_HELP"},
			std::pair{SDL_SCANCODE_MENU,"SDL_SCANCODE_MENU"},
			std::pair{SDL_SCANCODE_SELECT,"SDL_SCANCODE_SELECT"},
			std::pair{SDL_SCANCODE_STOP,"SDL_SCANCODE_STOP"},
			std::pair{SDL_SCANCODE_AGAIN,"SDL_SCANCODE_AGAIN"},
			std::pair{SDL_SCANCODE_UNDO,"SDL_SCANCODE_UNDO"},
			std::pair{SDL_SCANCODE_CUT,"SDL_SCANCODE_CUT"},
			std::pair{SDL_SCANCODE_COPY,"SDL_SCANCODE_COPY"},
			std::pair{SDL_SCANCODE_PASTE,"SDL_SCANCODE_PASTE"},
			std::pair{SDL_SCANCODE_FIND,"SDL_SCANCODE_FIND"},
			std::pair{SDL_SCANCODE_MUTE,"SDL_SCANCODE_MUTE"},
			std::pair{SDL_SCANCODE_VOLUMEUP,"SDL_SCANCODE_VOLUMEUP"},
			std::pair{SDL_SCANCODE_VOLUMEDOWN,"SDL_SCANCODE_VOLUMEDOWN"},
			std::pair{SDL_SCANCODE_KP_COMMA,"SDL_SCANCODE_KP_COMMA"},
			std::pair{SDL_SCANCODE_KP_EQUALSAS400,"SDL_SCANCODE_KP_EQUALSAS400"},
			std::pair{SDL_SCANCODE_INTERNATIONAL1,"SDL_SCANCODE_INTERNATIONAL1"},
			std::pair{SDL_SCANCODE_INTERNATIONAL2,"SDL_SCANCODE_INTERNATIONAL2"},
			std::pair{SDL_SCANCODE_INTERNATIONAL3,"SDL_SCANCODE_INTERNATIONAL3"},
			std::pair{SDL_SCANCODE_INTERNATIONAL4,"SDL_SCANCODE_INTERNATIONAL4"},
			std::pair{SDL_SCANCODE_INTERNATIONAL5,"SDL_SCANCODE_INTERNATIONAL5"},
			std::pair{SDL_SCANCODE_INTERNATIONAL6,"SDL_SCANCODE_INTERNATIONAL6"},
			std::pair{SDL_SCANCODE_INTERNATIONAL7,"SDL_SCANCODE_INTERNATIONAL7"},
			std::pair{SDL_SCANCODE_INTERNATIONAL8,"SDL_SCANCODE_INTERNATIONAL8"},
			std::pair{SDL_SCANCODE_INTERNATIONAL9,"SDL_SCANCODE_INTERNATIONAL9"},
			std::pair{SDL_SCANCODE_LANG1,"SDL_SCANCODE_LANG1"},
			std::pair{SDL_SCANCODE_LANG2,"SDL_SCANCODE_LANG2"},
			std::pair{SDL_SCANCODE_LANG3,"SDL_SCANCODE_LANG3"},
			std::pair{SDL_SCANCODE_LANG4,"SDL_SCANCODE_LANG4"},
			std::pair{SDL_SCANCODE_LANG5,"SDL_SCANCODE_LANG5"},
			std::pair{SDL_SCANCODE_LANG6,"SDL_SCANCODE_LANG6"},
			std::pair{SDL_SCANCODE_LANG7,"SDL_SCANCODE_LANG7"},
			std::pair{SDL_SCANCODE_LANG8,"SDL_SCANCODE_LANG8"},
			std::pair{SDL_SCANCODE_LANG9,"SDL_SCANCODE_LANG9"},
			std::pair{SDL_SCANCODE_ALTERASE,"SDL_SCANCODE_ALTERASE"},
			std::pair{SDL_SCANCODE_SYSREQ,"SDL_SCANCODE_SYSREQ"},
			std::pair{SDL_SCANCODE_CANCEL,"SDL_SCANCODE_CANCEL"},
			std::pair{SDL_SCANCODE_CLEAR,"SDL_SCANCODE_CLEAR"},
			std::pair{SDL_SCANCODE_PRIOR,"SDL_SCANCODE_PRIOR"},
			std::pair{SDL_SCANCODE_RETURN2,"SDL_SCANCODE_RETURN2"},
			std::pair{SDL_SCANCODE_SEPARATOR,"SDL_SCANCODE_SEPARATOR"},
			std::pair{SDL_SCANCODE_OUT,"SDL_SCANCODE_OUT"},
			std::pair{SDL_SCANCODE_OPER,"SDL_SCANCODE_OPER"},
			std::pair{SDL_SCANCODE_CLEARAGAIN,"SDL_SCANCODE_CLEARAGAIN"},
			std::pair{SDL_SCANCODE_CRSEL,"SDL_SCANCODE_CRSEL"},
			std::pair{SDL_SCANCODE_EXSEL,"SDL_SCANCODE_EXSEL"},
			std::pair{SDL_SCANCODE_KP_00,"SDL_SCANCODE_KP_00"},
			std::pair{SDL_SCANCODE_KP_000,"SDL_SCANCODE_KP_000"},
			std::pair{SDL_SCANCODE_THOUSANDSSEPARATOR,"SDL_SCANCODE_THOUSANDSSEPARATOR"},
			std::pair{SDL_SCANCODE_DECIMALSEPARATOR,"SDL_SCANCODE_DECIMALSEPARATOR"},
			std::pair{SDL_SCANCODE_CURRENCYUNIT,"SDL_SCANCODE_CURRENCYUNIT"},
			std::pair{SDL_SCANCODE_CURRENCYSUBUNIT,"SDL_SCANCODE_CURRENCYSUBUNIT"},
			std::pair{SDL_SCANCODE_KP_LEFTPAREN,"SDL_SCANCODE_KP_LEFTPAREN"},
			std::pair{SDL_SCANCODE_KP_RIGHTPAREN,"SDL_SCANCODE_KP_RIGHTPAREN"},
			std::pair{SDL_SCANCODE_KP_LEFTBRACE,"SDL_SCANCODE_KP_LEFTBRACE"},
			std::pair{SDL_SCANCODE_KP_RIGHTBRACE,"SDL_SCANCODE_KP_RIGHTBRACE"},
			std::pair{SDL_SCANCODE_KP_TAB,"SDL_SCANCODE_KP_TAB"},
			std::pair{SDL_SCANCODE_KP_BACKSPACE,"SDL_SCANCODE_KP_BACKSPACE"},
			std::pair{SDL_SCANCODE_KP_A,"SDL_SCANCODE_KP_A"},
			std::pair{SDL_SCANCODE_KP_B,"SDL_SCANCODE_KP_B"},
			std::pair{SDL_SCANCODE_KP_C,"SDL_SCANCODE_KP_C"},
			std::pair{SDL_SCANCODE_KP_D,"SDL_SCANCODE_KP_D"},
			std::pair{SDL_SCANCODE_KP_E,"SDL_SCANCODE_KP_E"},
			std::pair{SDL_SCANCODE_KP_F,"SDL_SCANCODE_KP_F"},
			std::pair{SDL_SCANCODE_KP_XOR,"SDL_SCANCODE_KP_XOR"},
			std::pair{SDL_SCANCODE_KP_POWER,"SDL_SCANCODE_KP_POWER"},
			std::pair{SDL_SCANCODE_KP_PERCENT,"SDL_SCANCODE_KP_PERCENT"},
			std::pair{SDL_SCANCODE_KP_LESS,"SDL_SCANCODE_KP_LESS"},
			std::pair{SDL_SCANCODE_KP_GREATER,"SDL_SCANCODE_KP_GREATER"},
			std::pair{SDL_SCANCODE_KP_AMPERSAND,"SDL_SCANCODE_KP_AMPERSAND"},
			std::pair{SDL_SCANCODE_KP_DBLAMPERSAND,"SDL_SCANCODE_KP_DBLAMPERSAND"},
			std::pair{SDL_SCANCODE_KP_VERTICALBAR,"SDL_SCANCODE_KP_VERTICALBAR"},
			std::pair{SDL_SCANCODE_KP_DBLVERTICALBAR,"SDL_SCANCODE_KP_DBLVERTICALBAR"},
			std::pair{SDL_SCANCODE_KP_COLON,"SDL_SCANCODE_KP_COLON"},
			std::pair{SDL_SCANCODE_KP_HASH,"SDL_SCANCODE_KP_HASH"},
			std::pair{SDL_SCANCODE_KP_SPACE,"SDL_SCANCODE_KP_SPACE"},
			std::pair{SDL_SCANCODE_KP_AT,"SDL_SCANCODE_KP_AT"},
			std::pair{SDL_SCANCODE_KP_EXCLAM,"SDL_SCANCODE_KP_EXCLAM"},
			std::pair{SDL_SCANCODE_KP_MEMSTORE,"SDL_SCANCODE_KP_MEMSTORE"},
			std::pair{SDL_SCANCODE_KP_MEMRECALL,"SDL_SCANCODE_KP_MEMRECALL"},
			std::pair{SDL_SCANCODE_KP_MEMCLEAR,"SDL_SCANCODE_KP_MEMCLEAR"},
			std::pair{SDL_SCANCODE_KP_MEMADD,"SDL_SCANCODE_KP_MEMADD"},
			std::pair{SDL_SCANCODE_KP_MEMSUBTRACT,"SDL_SCANCODE_KP_MEMSUBTRACT"},
			std::pair{SDL_SCANCODE_KP_MEMMULTIPLY,"SDL_SCANCODE_KP_MEMMULTIPLY"},
			std::pair{SDL_SCANCODE_KP_MEMDIVIDE,"SDL_SCANCODE_KP_MEMDIVIDE"},
			std::pair{SDL_SCANCODE_KP_PLUSMINUS,"SDL_SCANCODE_KP_PLUSMINUS"},
			std::pair{SDL_SCANCODE_KP_CLEAR,"SDL_SCANCODE_KP_CLEAR"},
			std::pair{SDL_SCANCODE_KP_CLEARENTRY,"SDL_SCANCODE_KP_CLEARENTRY"},
			std::pair{SDL_SCANCODE_KP_BINARY,"SDL_SCANCODE_KP_BINARY"},
			std::pair{SDL_SCANCODE_KP_OCTAL,"SDL_SCANCODE_KP_OCTAL"},
			std::pair{SDL_SCANCODE_KP_DECIMAL,"SDL_SCANCODE_KP_DECIMAL"},
			std::pair{SDL_SCANCODE_KP_HEXADECIMAL,"SDL_SCANCODE_KP_HEXADECIMAL"},
			std::pair{SDL_SCANCODE_LCTRL,"SDL_SCANCODE_LCTRL"},
			std::pair{SDL_SCANCODE_LSHIFT,"SDL_SCANCODE_LSHIFT"},
			std::pair{SDL_SCANCODE_LALT,"SDL_SCANCODE_LALT"},
			std::pair{SDL_SCANCODE_LGUI,"SDL_SCANCODE_LGUI"},
			std::pair{SDL_SCANCODE_RCTRL,"SDL_SCANCODE_RCTRL"},
			std::pair{SDL_SCANCODE_RSHIFT,"SDL_SCANCODE_RSHIFT"},
			std::pair{SDL_SCANCODE_RALT,"SDL_SCANCODE_RALT"},
			std::pair{SDL_SCANCODE_RGUI,"SDL_SCANCODE_RGUI"},
			std::pair{SDL_SCANCODE_MODE,"SDL_SCANCODE_MODE"},
			std::pair{SDL_SCANCODE_SLEEP,"SDL_SCANCODE_SLEEP"},
			std::pair{SDL_SCANCODE_WAKE,"SDL_SCANCODE_WAKE"},
			std::pair{SDL_SCANCODE_CHANNEL_INCREMENT,"SDL_SCANCODE_CHANNEL_INCREMENT"},
			std::pair{SDL_SCANCODE_CHANNEL_DECREMENT,"SDL_SCANCODE_CHANNEL_DECREMENT"},
			std::pair{SDL_SCANCODE_MEDIA_PLAY,"SDL_SCANCODE_MEDIA_PLAY"},
			std::pair{SDL_SCANCODE_MEDIA_PAUSE,"SDL_SCANCODE_MEDIA_PAUSE"},
			std::pair{SDL_SCANCODE_MEDIA_RECORD,"SDL_SCANCODE_MEDIA_RECORD"},
			std::pair{SDL_SCANCODE_MEDIA_FAST_FORWARD,"SDL_SCANCODE_MEDIA_FAST_FORWARD"},
			std::pair{SDL_SCANCODE_MEDIA_REWIND,"SDL_SCANCODE_MEDIA_REWIND"},
			std::pair{SDL_SCANCODE_MEDIA_NEXT_TRACK,"SDL_SCANCODE_MEDIA_NEXT_TRACK"},
			std::pair{SDL_SCANCODE_MEDIA_PREVIOUS_TRACK,"SDL_SCANCODE_MEDIA_PREVIOUS_TRACK"},
			std::pair{SDL_SCANCODE_MEDIA_STOP,"SDL_SCANCODE_MEDIA_STOP"},
			std::pair{SDL_SCANCODE_MEDIA_EJECT,"SDL_SCANCODE_MEDIA_EJECT"},
			std::pair{SDL_SCANCODE_MEDIA_PLAY_PAUSE,"SDL_SCANCODE_MEDIA_PLAY_PAUSE"},
			std::pair{SDL_SCANCODE_MEDIA_SELECT,"SDL_SCANCODE_MEDIA_SELECT"},
			std::pair{SDL_SCANCODE_AC_NEW,"SDL_SCANCODE_AC_NEW"},
			std::pair{SDL_SCANCODE_AC_OPEN,"SDL_SCANCODE_AC_OPEN"},
			std::pair{SDL_SCANCODE_AC_CLOSE,"SDL_SCANCODE_AC_CLOSE"},
			std::pair{SDL_SCANCODE_AC_EXIT,"SDL_SCANCODE_AC_EXIT"},
			std::pair{SDL_SCANCODE_AC_SAVE,"SDL_SCANCODE_AC_SAVE"},
			std::pair{SDL_SCANCODE_AC_PRINT,"SDL_SCANCODE_AC_PRINT"},
			std::pair{SDL_SCANCODE_AC_PROPERTIES,"SDL_SCANCODE_AC_PROPERTIES"},
			std::pair{SDL_SCANCODE_AC_SEARCH,"SDL_SCANCODE_AC_SEARCH"},
			std::pair{SDL_SCANCODE_AC_HOME,"SDL_SCANCODE_AC_HOME"},
			std::pair{SDL_SCANCODE_AC_BACK,"SDL_SCANCODE_AC_BACK"},
			std::pair{SDL_SCANCODE_AC_FORWARD,"SDL_SCANCODE_AC_FORWARD"},
			std::pair{SDL_SCANCODE_AC_STOP,"SDL_SCANCODE_AC_STOP"},
			std::pair{SDL_SCANCODE_AC_REFRESH,"SDL_SCANCODE_AC_REFRESH"},
			std::pair{SDL_SCANCODE_AC_BOOKMARKS,"SDL_SCANCODE_AC_BOOKMARKS"},
			std::pair{SDL_SCANCODE_SOFTLEFT,"SDL_SCANCODE_SOFTLEFT"},
			std::pair{SDL_SCANCODE_SOFTRIGHT,"SDL_SCANCODE_SOFTRIGHT"},
			std::pair{SDL_SCANCODE_CALL,"SDL_SCANCODE_CALL"},
			std::pair{SDL_SCANCODE_ENDCALL,"SDL_SCANCODE_ENDCALL"},
			std::pair{SDL_SCANCODE_RESERVED,"SDL_SCANCODE_RESERVED"},
			std::pair{SDL_SCANCODE_COUNT,"SDL_SCANCODE_COUNT"}
		};

		return scancode_arr;
	}

	inline static const auto &get_keycode_table() noexcept{
		static const std::array keycode_arr = {
			std::pair{SDLK_EXTENDED_MASK,"SDLK_EXTENDED_MASK"},
			std::pair{SDLK_SCANCODE_MASK,"SDLK_SCANCODE_MASK"},
			std::pair{SDLK_UNKNOWN,"SDLK_UNKNOWN"},
			std::pair{SDLK_RETURN,"SDLK_RETURN"},
			std::pair{SDLK_ESCAPE,"SDLK_ESCAPE"},
			std::pair{SDLK_BACKSPACE,"SDLK_BACKSPACE"},
			std::pair{SDLK_TAB,"SDLK_TAB"},
			std::pair{SDLK_SPACE,"SDLK_SPACE"},
			std::pair{SDLK_EXCLAIM,"SDLK_EXCLAIM"},
			std::pair{SDLK_DBLAPOSTROPHE,"SDLK_DBLAPOSTROPHE"},
			std::pair{SDLK_HASH,"SDLK_HASH"},
			std::pair{SDLK_DOLLAR,"SDLK_DOLLAR"},
			std::pair{SDLK_PERCENT,"SDLK_PERCENT"},
			std::pair{SDLK_AMPERSAND,"SDLK_AMPERSAND"},
			std::pair{SDLK_APOSTROPHE,"SDLK_APOSTROPHE"},
			std::pair{SDLK_LEFTPAREN,"SDLK_LEFTPAREN"},
			std::pair{SDLK_RIGHTPAREN,"SDLK_RIGHTPAREN"},
			std::pair{SDLK_ASTERISK,"SDLK_ASTERISK"},
			std::pair{SDLK_PLUS,"SDLK_PLUS"},
			std::pair{SDLK_COMMA,"SDLK_COMMA"},
			std::pair{SDLK_MINUS,"SDLK_MINUS"},
			std::pair{SDLK_PERIOD,"SDLK_PERIOD"},
			std::pair{SDLK_SLASH,"SDLK_SLASH"},
			std::pair{SDLK_0,"SDLK_0"},
			std::pair{SDLK_1,"SDLK_1"},
			std::pair{SDLK_2,"SDLK_2"},
			std::pair{SDLK_3,"SDLK_3"},
			std::pair{SDLK_4,"SDLK_4"},
			std::pair{SDLK_5,"SDLK_5"},
			std::pair{SDLK_6,"SDLK_6"},
			std::pair{SDLK_7,"SDLK_7"},
			std::pair{SDLK_8,"SDLK_8"},
			std::pair{SDLK_9,"SDLK_9"},
			std::pair{SDLK_COLON,"SDLK_COLON"},
			std::pair{SDLK_SEMICOLON,"SDLK_SEMICOLON"},
			std::pair{SDLK_LESS,"SDLK_LESS"},
			std::pair{SDLK_EQUALS,"SDLK_EQUALS"},
			std::pair{SDLK_GREATER,"SDLK_GREATER"},
			std::pair{SDLK_QUESTION,"SDLK_QUESTION"},
			std::pair{SDLK_AT,"SDLK_AT"},
			std::pair{SDLK_LEFTBRACKET,"SDLK_LEFTBRACKET"},
			std::pair{SDLK_BACKSLASH,"SDLK_BACKSLASH"},
			std::pair{SDLK_RIGHTBRACKET,"SDLK_RIGHTBRACKET"},
			std::pair{SDLK_CARET,"SDLK_CARET"},
			std::pair{SDLK_UNDERSCORE,"SDLK_UNDERSCORE"},
			std::pair{SDLK_GRAVE,"SDLK_GRAVE"},
			std::pair{SDLK_A,"SDLK_A"},
			std::pair{SDLK_B,"SDLK_B"},
			std::pair{SDLK_C,"SDLK_C"},
			std::pair{SDLK_D,"SDLK_D"},
			std::pair{SDLK_E,"SDLK_E"},
			std::pair{SDLK_F,"SDLK_F"},
			std::pair{SDLK_G,"SDLK_G"},
			std::pair{SDLK_H,"SDLK_H"},
			std::pair{SDLK_I,"SDLK_I"},
			std::pair{SDLK_J,"SDLK_J"},
			std::pair{SDLK_K,"SDLK_K"},
			std::pair{SDLK_L,"SDLK_L"},
			std::pair{SDLK_M,"SDLK_M"},
			std::pair{SDLK_N,"SDLK_N"},
			std::pair{SDLK_O,"SDLK_O"},
			std::pair{SDLK_P,"SDLK_P"},
			std::pair{SDLK_Q,"SDLK_Q"},
			std::pair{SDLK_R,"SDLK_R"},
			std::pair{SDLK_S,"SDLK_S"},
			std::pair{SDLK_T,"SDLK_T"},
			std::pair{SDLK_U,"SDLK_U"},
			std::pair{SDLK_V,"SDLK_V"},
			std::pair{SDLK_W,"SDLK_W"},
			std::pair{SDLK_X,"SDLK_X"},
			std::pair{SDLK_Y,"SDLK_Y"},
			std::pair{SDLK_Z,"SDLK_Z"},
			std::pair{SDLK_LEFTBRACE,"SDLK_LEFTBRACE"},
			std::pair{SDLK_PIPE,"SDLK_PIPE"},
			std::pair{SDLK_RIGHTBRACE,"SDLK_RIGHTBRACE"},
			std::pair{SDLK_TILDE,"SDLK_TILDE"},
			std::pair{SDLK_DELETE,"SDLK_DELETE"},
			std::pair{SDLK_PLUSMINUS,"SDLK_PLUSMINUS"},
			std::pair{SDLK_CAPSLOCK,"SDLK_CAPSLOCK"},
			std::pair{SDLK_F1,"SDLK_F1"},
			std::pair{SDLK_F2,"SDLK_F2"},
			std::pair{SDLK_F3,"SDLK_F3"},
			std::pair{SDLK_F4,"SDLK_F4"},
			std::pair{SDLK_F5,"SDLK_F5"},
			std::pair{SDLK_F6,"SDLK_F6"},
			std::pair{SDLK_F7,"SDLK_F7"},
			std::pair{SDLK_F8,"SDLK_F8"},
			std::pair{SDLK_F9,"SDLK_F9"},
			std::pair{SDLK_F10,"SDLK_F10"},
			std::pair{SDLK_F11,"SDLK_F11"},
			std::pair{SDLK_F12,"SDLK_F12"},
			std::pair{SDLK_PRINTSCREEN,"SDLK_PRINTSCREEN"},
			std::pair{SDLK_SCROLLLOCK,"SDLK_SCROLLLOCK"},
			std::pair{SDLK_PAUSE,"SDLK_PAUSE"},
			std::pair{SDLK_INSERT,"SDLK_INSERT"},
			std::pair{SDLK_HOME,"SDLK_HOME"},
			std::pair{SDLK_PAGEUP,"SDLK_PAGEUP"},
			std::pair{SDLK_END,"SDLK_END"},
			std::pair{SDLK_PAGEDOWN,"SDLK_PAGEDOWN"},
			std::pair{SDLK_RIGHT,"SDLK_RIGHT"},
			std::pair{SDLK_LEFT,"SDLK_LEFT"},
			std::pair{SDLK_DOWN,"SDLK_DOWN"},
			std::pair{SDLK_UP,"SDLK_UP"},
			std::pair{SDLK_NUMLOCKCLEAR,"SDLK_NUMLOCKCLEAR"},
			std::pair{SDLK_KP_DIVIDE,"SDLK_KP_DIVIDE"},
			std::pair{SDLK_KP_MULTIPLY,"SDLK_KP_MULTIPLY"},
			std::pair{SDLK_KP_MINUS,"SDLK_KP_MINUS"},
			std::pair{SDLK_KP_PLUS,"SDLK_KP_PLUS"},
			std::pair{SDLK_KP_ENTER,"SDLK_KP_ENTER"},
			std::pair{SDLK_KP_1,"SDLK_KP_1"},
			std::pair{SDLK_KP_2,"SDLK_KP_2"},
			std::pair{SDLK_KP_3,"SDLK_KP_3"},
			std::pair{SDLK_KP_4,"SDLK_KP_4"},
			std::pair{SDLK_KP_5,"SDLK_KP_5"},
			std::pair{SDLK_KP_6,"SDLK_KP_6"},
			std::pair{SDLK_KP_7,"SDLK_KP_7"},
			std::pair{SDLK_KP_8,"SDLK_KP_8"},
			std::pair{SDLK_KP_9,"SDLK_KP_9"},
			std::pair{SDLK_KP_0,"SDLK_KP_0"},
			std::pair{SDLK_KP_PERIOD,"SDLK_KP_PERIOD"},
			std::pair{SDLK_APPLICATION,"SDLK_APPLICATION"},
			std::pair{SDLK_POWER,"SDLK_POWER"},
			std::pair{SDLK_KP_EQUALS,"SDLK_KP_EQUALS"},
			std::pair{SDLK_F13,"SDLK_F13"},
			std::pair{SDLK_F14,"SDLK_F14"},
			std::pair{SDLK_F15,"SDLK_F15"},
			std::pair{SDLK_F16,"SDLK_F16"},
			std::pair{SDLK_F17,"SDLK_F17"},
			std::pair{SDLK_F18,"SDLK_F18"},
			std::pair{SDLK_F19,"SDLK_F19"},
			std::pair{SDLK_F20,"SDLK_F20"},
			std::pair{SDLK_F21,"SDLK_F21"},
			std::pair{SDLK_F22,"SDLK_F22"},
			std::pair{SDLK_F23,"SDLK_F23"},
			std::pair{SDLK_F24,"SDLK_F24"},
			std::pair{SDLK_EXECUTE,"SDLK_EXECUTE"},
			std::pair{SDLK_HELP,"SDLK_HELP"},
			std::pair{SDLK_MENU,"SDLK_MENU"},
			std::pair{SDLK_SELECT,"SDLK_SELECT"},
			std::pair{SDLK_STOP,"SDLK_STOP"},
			std::pair{SDLK_AGAIN,"SDLK_AGAIN"},
			std::pair{SDLK_UNDO,"SDLK_UNDO"},
			std::pair{SDLK_CUT,"SDLK_CUT"},
			std::pair{SDLK_COPY,"SDLK_COPY"},
			std::pair{SDLK_PASTE,"SDLK_PASTE"},
			std::pair{SDLK_FIND,"SDLK_FIND"},
			std::pair{SDLK_MUTE,"SDLK_MUTE"},
			std::pair{SDLK_VOLUMEUP,"SDLK_VOLUMEUP"},
			std::pair{SDLK_VOLUMEDOWN,"SDLK_VOLUMEDOWN"},
			std::pair{SDLK_KP_COMMA,"SDLK_KP_COMMA"},
			std::pair{SDLK_KP_EQUALSAS400,"SDLK_KP_EQUALSAS400"},
			std::pair{SDLK_ALTERASE,"SDLK_ALTERASE"},
			std::pair{SDLK_SYSREQ,"SDLK_SYSREQ"},
			std::pair{SDLK_CANCEL,"SDLK_CANCEL"},
			std::pair{SDLK_CLEAR,"SDLK_CLEAR"},
			std::pair{SDLK_PRIOR,"SDLK_PRIOR"},
			std::pair{SDLK_RETURN2,"SDLK_RETURN2"},
			std::pair{SDLK_SEPARATOR,"SDLK_SEPARATOR"},
			std::pair{SDLK_OUT,"SDLK_OUT"},
			std::pair{SDLK_OPER,"SDLK_OPER"},
			std::pair{SDLK_CLEARAGAIN,"SDLK_CLEARAGAIN"},
			std::pair{SDLK_CRSEL,"SDLK_CRSEL"},
			std::pair{SDLK_EXSEL,"SDLK_EXSEL"},
			std::pair{SDLK_KP_00,"SDLK_KP_00"},
			std::pair{SDLK_KP_000,"SDLK_KP_000"},
			std::pair{SDLK_THOUSANDSSEPARATOR,"SDLK_THOUSANDSSEPARATOR"},
			std::pair{SDLK_DECIMALSEPARATOR,"SDLK_DECIMALSEPARATOR"},
			std::pair{SDLK_CURRENCYUNIT,"SDLK_CURRENCYUNIT"},
			std::pair{SDLK_CURRENCYSUBUNIT,"SDLK_CURRENCYSUBUNIT"},
			std::pair{SDLK_KP_LEFTPAREN,"SDLK_KP_LEFTPAREN"},
			std::pair{SDLK_KP_RIGHTPAREN,"SDLK_KP_RIGHTPAREN"},
			std::pair{SDLK_KP_LEFTBRACE,"SDLK_KP_LEFTBRACE"},
			std::pair{SDLK_KP_RIGHTBRACE,"SDLK_KP_RIGHTBRACE"},
			std::pair{SDLK_KP_TAB,"SDLK_KP_TAB"},
			std::pair{SDLK_KP_BACKSPACE,"SDLK_KP_BACKSPACE"},
			std::pair{SDLK_KP_A,"SDLK_KP_A"},
			std::pair{SDLK_KP_B,"SDLK_KP_B"},
			std::pair{SDLK_KP_C,"SDLK_KP_C"},
			std::pair{SDLK_KP_D,"SDLK_KP_D"},
			std::pair{SDLK_KP_E,"SDLK_KP_E"},
			std::pair{SDLK_KP_F,"SDLK_KP_F"},
			std::pair{SDLK_KP_XOR,"SDLK_KP_XOR"},
			std::pair{SDLK_KP_POWER,"SDLK_KP_POWER"},
			std::pair{SDLK_KP_PERCENT,"SDLK_KP_PERCENT"},
			std::pair{SDLK_KP_LESS,"SDLK_KP_LESS"},
			std::pair{SDLK_KP_GREATER,"SDLK_KP_GREATER"},
			std::pair{SDLK_KP_AMPERSAND,"SDLK_KP_AMPERSAND"},
			std::pair{SDLK_KP_DBLAMPERSAND,"SDLK_KP_DBLAMPERSAND"},
			std::pair{SDLK_KP_VERTICALBAR,"SDLK_KP_VERTICALBAR"},
			std::pair{SDLK_KP_DBLVERTICALBAR,"SDLK_KP_DBLVERTICALBAR"},
			std::pair{SDLK_KP_COLON,"SDLK_KP_COLON"},
			std::pair{SDLK_KP_HASH,"SDLK_KP_HASH"},
			std::pair{SDLK_KP_SPACE,"SDLK_KP_SPACE"},
			std::pair{SDLK_KP_AT,"SDLK_KP_AT"},
			std::pair{SDLK_KP_EXCLAM,"SDLK_KP_EXCLAM"},
			std::pair{SDLK_KP_MEMSTORE,"SDLK_KP_MEMSTORE"},
			std::pair{SDLK_KP_MEMRECALL,"SDLK_KP_MEMRECALL"},
			std::pair{SDLK_KP_MEMCLEAR,"SDLK_KP_MEMCLEAR"},
			std::pair{SDLK_KP_MEMADD,"SDLK_KP_MEMADD"},
			std::pair{SDLK_KP_MEMSUBTRACT,"SDLK_KP_MEMSUBTRACT"},
			std::pair{SDLK_KP_MEMMULTIPLY,"SDLK_KP_MEMMULTIPLY"},
			std::pair{SDLK_KP_MEMDIVIDE,"SDLK_KP_MEMDIVIDE"},
			std::pair{SDLK_KP_PLUSMINUS,"SDLK_KP_PLUSMINUS"},
			std::pair{SDLK_KP_CLEAR,"SDLK_KP_CLEAR"},
			std::pair{SDLK_KP_CLEARENTRY,"SDLK_KP_CLEARENTRY"},
			std::pair{SDLK_KP_BINARY,"SDLK_KP_BINARY"},
			std::pair{SDLK_KP_OCTAL,"SDLK_KP_OCTAL"},
			std::pair{SDLK_KP_DECIMAL,"SDLK_KP_DECIMAL"},
			std::pair{SDLK_KP_HEXADECIMAL,"SDLK_KP_HEXADECIMAL"},
			std::pair{SDLK_LCTRL,"SDLK_LCTRL"},
			std::pair{SDLK_LSHIFT,"SDLK_LSHIFT"},
			std::pair{SDLK_LALT,"SDLK_LALT"},
			std::pair{SDLK_LGUI,"SDLK_LGUI"},
			std::pair{SDLK_RCTRL,"SDLK_RCTRL"},
			std::pair{SDLK_RSHIFT,"SDLK_RSHIFT"},
			std::pair{SDLK_RALT,"SDLK_RALT"},
			std::pair{SDLK_RGUI,"SDLK_RGUI"},
			std::pair{SDLK_MODE,"SDLK_MODE"},
			std::pair{SDLK_SLEEP,"SDLK_SLEEP"},
			std::pair{SDLK_WAKE,"SDLK_WAKE"},
			std::pair{SDLK_CHANNEL_INCREMENT,"SDLK_CHANNEL_INCREMENT"},
			std::pair{SDLK_CHANNEL_DECREMENT,"SDLK_CHANNEL_DECREMENT"},
			std::pair{SDLK_MEDIA_PLAY,"SDLK_MEDIA_PLAY"},
			std::pair{SDLK_MEDIA_PAUSE,"SDLK_MEDIA_PAUSE"},
			std::pair{SDLK_MEDIA_RECORD,"SDLK_MEDIA_RECORD"},
			std::pair{SDLK_MEDIA_FAST_FORWARD,"SDLK_MEDIA_FAST_FORWARD"},
			std::pair{SDLK_MEDIA_REWIND,"SDLK_MEDIA_REWIND"},
			std::pair{SDLK_MEDIA_NEXT_TRACK,"SDLK_MEDIA_NEXT_TRACK"},
			std::pair{SDLK_MEDIA_PREVIOUS_TRACK,"SDLK_MEDIA_PREVIOUS_TRACK"},
			std::pair{SDLK_MEDIA_STOP,"SDLK_MEDIA_STOP"},
			std::pair{SDLK_MEDIA_EJECT,"SDLK_MEDIA_EJECT"},
			std::pair{SDLK_MEDIA_PLAY_PAUSE,"SDLK_MEDIA_PLAY_PAUSE"},
			std::pair{SDLK_MEDIA_SELECT,"SDLK_MEDIA_SELECT"},
			std::pair{SDLK_AC_NEW,"SDLK_AC_NEW"},
			std::pair{SDLK_AC_OPEN,"SDLK_AC_OPEN"},
			std::pair{SDLK_AC_CLOSE,"SDLK_AC_CLOSE"},
			std::pair{SDLK_AC_EXIT,"SDLK_AC_EXIT"},
			std::pair{SDLK_AC_SAVE,"SDLK_AC_SAVE"},
			std::pair{SDLK_AC_PRINT,"SDLK_AC_PRINT"},
			std::pair{SDLK_AC_PROPERTIES,"SDLK_AC_PROPERTIES"},
			std::pair{SDLK_AC_SEARCH,"SDLK_AC_SEARCH"},
			std::pair{SDLK_AC_HOME,"SDLK_AC_HOME"},
			std::pair{SDLK_AC_BACK,"SDLK_AC_BACK"},
			std::pair{SDLK_AC_FORWARD,"SDLK_AC_FORWARD"},
			std::pair{SDLK_AC_STOP,"SDLK_AC_STOP"},
			std::pair{SDLK_AC_REFRESH,"SDLK_AC_REFRESH"},
			std::pair{SDLK_AC_BOOKMARKS,"SDLK_AC_BOOKMARKS"},
			std::pair{SDLK_SOFTLEFT,"SDLK_SOFTLEFT"},
			std::pair{SDLK_SOFTRIGHT,"SDLK_SOFTRIGHT"},
			std::pair{SDLK_CALL,"SDLK_CALL"},
			std::pair{SDLK_ENDCALL,"SDLK_ENDCALL"},
			std::pair{SDLK_LEFT_TAB,"SDLK_LEFT_TAB"},
			std::pair{SDLK_LEVEL5_SHIFT,"SDLK_LEVEL5_SHIFT"},
			std::pair{SDLK_MULTI_KEY_COMPOSE,"SDLK_MULTI_KEY_COMPOSE"},
			std::pair{SDLK_LMETA,"SDLK_LMETA"},
			std::pair{SDLK_RMETA,"SDLK_RMETA"},
			std::pair{SDLK_LHYPER,"SDLK_LHYPER"},
			std::pair{SDLK_RHYPER,"SDLK_RHYPER"}
		};
	
		return keycode_arr;
	}

	inline static const auto &get_keymod_table() noexcept{
		static const std::array keymod_arr = {
			std::pair{SDL_KMOD_NONE,"SDL_KMOD_NONE"},
			std::pair{SDL_KMOD_LSHIFT,"SDL_KMOD_LSHIFT"},
			std::pair{SDL_KMOD_RSHIFT,"SDL_KMOD_RSHIFT"},
			std::pair{SDL_KMOD_LEVEL5,"SDL_KMOD_LEVEL5"},
			std::pair{SDL_KMOD_LCTRL,"SDL_KMOD_LCTRL"},
			std::pair{SDL_KMOD_RCTRL,"SDL_KMOD_RCTRL"},
			std::pair{SDL_KMOD_LALT,"SDL_KMOD_LALT"},
			std::pair{SDL_KMOD_RALT,"SDL_KMOD_RALT"},
			std::pair{SDL_KMOD_LGUI,"SDL_KMOD_LGUI"},
			std::pair{SDL_KMOD_RGUI,"SDL_KMOD_RGUI"},
			std::pair{SDL_KMOD_NUM,"SDL_KMOD_NUM"},
			std::pair{SDL_KMOD_CAPS,"SDL_KMOD_CAPS"},
			std::pair{SDL_KMOD_MODE,"SDL_KMOD_MODE"},
			std::pair{SDL_KMOD_SCROLL,"SDL_KMOD_SCROLL"},
			//std::pair{SDL_KMOD_CTRL,"SDL_KMOD_CTRL"},
			//std::pair{SDL_KMOD_SHIFT,"SDL_KMOD_SHIFT"},
			//std::pair{SDL_KMOD_ALT,"SDL_KMOD_ALT"},
			//std::pair{SDL_KMOD_GUI,"SDL_KMOD_GUI"}
		};
	
		return keymod_arr;
	}



}


namespace core{
	inline const char *get_name_sdl_event_type(Uint32 type) noexcept{
		auto table = get_event_type_table();
		std::unordered_map<Uint32,const char*> v(table.begin(),table.end(),table.size());

		auto element = v.find(type);
		if (element != v.end()){
			return (*element).second;
		}else{
			return nullptr;
		}
	}

	inline const char *get_name_sdl_keycode(Uint32 type) noexcept{
		auto table = get_keycode_table();
		std::unordered_map<Uint32,const char*> v(table.begin(),table.end(),table.size());

		auto element = v.find(type);
		if (element != v.end()){
			return (*element).second;
		}else{
			return nullptr;
		}
	}

	inline const char *get_name_sdl_keymod(Uint32 type) noexcept{
		auto table = get_keymod_table();
		std::unordered_map<Uint32,const char*> v(table.begin(),table.end(),table.size());

		auto element = v.find(type);
		if (element != v.end()){
			return (*element).second;
		}else{
			return nullptr;
		}
	}

	inline const char *get_name_sdl_scancode(Uint32 type) noexcept{
		auto table = get_scancode_table();
		std::unordered_map<Uint32,const char*> v(table.begin(),table.end(),table.size());

		auto element = v.find(type);
		if (element != v.end()){
			return (*element).second;
		}else{
			return nullptr;
		}
	}

	inline const char *get_name_sdl_mouse_button_flags(SDL_MouseButtonFlags f) noexcept{
		switch(f){
			case (SDL_BUTTON_LEFT):return "SDL_BUTTON_LEFT";
			case (SDL_BUTTON_MIDDLE):return "SDL_BUTTON_MIDDLE";
			case (SDL_BUTTON_RIGHT):return "SDL_BUTTON_RIGHT";
			case (SDL_BUTTON_X1):return "SDL_BUTTON_X1";
			case (SDL_BUTTON_X2):return "SDL_BUTTON_X2";
			default:return nullptr;
		}
	}

	inline const char *get_name_sdl_power_state(SDL_PowerState f) noexcept{
		switch(f){
			case SDL_POWERSTATE_ERROR: return "SDL_POWERSTATE_ERROR";
			case SDL_POWERSTATE_UNKNOWN: return "SDL_POWERSTATE_UNKNOWN";
			case SDL_POWERSTATE_ON_BATTERY: return "SDL_POWERSTATE_ON_BATTERY";
			case SDL_POWERSTATE_NO_BATTERY: return "SDL_POWERSTATE_NO_BATTERY";
			case SDL_POWERSTATE_CHARGING: return "SDL_POWERSTATE_CHARGING";
			case SDL_POWERSTATE_CHARGED: return "SDL_POWERSTATE_CHARGED";
			default:return nullptr;
		}
	}

	inline const char *get_name_sdl_pen_input_flags(SDL_PenInputFlags f) noexcept{
		switch(f){
			case SDL_PEN_INPUT_DOWN:return "SDL_PEN_INPUT_DOWN";
			case SDL_PEN_INPUT_BUTTON_1:return "SDL_PEN_INPUT_BUTTON_1";
			case SDL_PEN_INPUT_BUTTON_2:return "SDL_PEN_INPUT_BUTTON_2";
			case SDL_PEN_INPUT_BUTTON_3:return "SDL_PEN_INPUT_BUTTON_3";
			case SDL_PEN_INPUT_BUTTON_4:return "SDL_PEN_INPUT_BUTTON_4";
			case SDL_PEN_INPUT_BUTTON_5:return "SDL_PEN_INPUT_BUTTON_5";
			case SDL_PEN_INPUT_ERASER_TIP:return "SDL_PEN_INPUT_ERASER_TIP";
			case SDL_PEN_INPUT_IN_PROXIMITY:return "SDL_PEN_INPUT_IN_PROXIMITY";
			default:return nullptr;
		}
	}

	inline const char *get_name_sdl_pen_axis(SDL_PenInputFlags f) noexcept{
		switch(f){
			case SDL_PEN_AXIS_PRESSURE:return "SDL_PEN_AXIS_PRESSURE";
			case SDL_PEN_AXIS_XTILT:return "SDL_PEN_AXIS_XTILT";
			case SDL_PEN_AXIS_YTILT:return "SDL_PEN_AXIS_YTILT";
			case SDL_PEN_AXIS_DISTANCE:return "SDL_PEN_AXIS_DISTANCE";
			case SDL_PEN_AXIS_ROTATION:return "SDL_PEN_AXIS_ROTATION";
			case SDL_PEN_AXIS_SLIDER:return "SDL_PEN_AXIS_SLIDER";
			case SDL_PEN_AXIS_TANGENTIAL_PRESSURE:return "SDL_PEN_AXIS_TANGENTIAL_PRESSURE";
			case SDL_PEN_AXIS_COUNT:return "SDL_PEN_AXIS_COUNT";
			default:return nullptr;
		}
	}

	template <typename LogT>
	void log_sdl_event(const SDL_Event &e, LogT &&Log = SDL_Log) noexcept{
		auto table = get_event_type_table();
		std::unordered_map<Uint32,const char*> v(table.begin(),table.end(),table.size());
		
		auto t = e.type;
		auto element = v.find(t);

		if (element != v.end()){
			do{
				if (start_with((*element).second,"SDL_EVENT_DISPLAY_")){
					Log("[log_sdl_event] %s displayID:%d",(*element).second,e.display.displayID);
					break;
				}

				if (start_with((*element).second,"SDL_EVENT_WINDOW_")){
					Log("[log_sdl_event] %s windowID:%d",(*element).second,e.window.windowID);
					break;
				}

				if (t == SDL_EVENT_KEYBOARD_ADDED || t == SDL_EVENT_KEYBOARD_REMOVED){
					Log("[log_sdl_event] %s keyboardID:%d",(*element).second,e.kdevice.which);
					break;
				}
				
				if (t == SDL_EVENT_KEY_DOWN || t == SDL_EVENT_KEY_UP){
					std::string s{};
					auto v = get_keymod_table();
					for(auto &&k :v){
						if (k.first & e.key.mod){
							if (!s.empty()){s += '|';}

							s += k.second;
						}
					}

					Log("[log_sdl_event] %s\t%s (%s) %s raw:%d windowID:%d keyboardID:%d",
						(*element).second,
						get_name_sdl_keycode(e.key.key),
						s.c_str(),
						get_name_sdl_scancode(e.key.scancode),
						e.key.raw,
						e.key.windowID,
						e.key.which
					);

					s.clear();
					break;
				}

				if (t == SDL_EVENT_TEXT_EDITING){
					Log("[log_sdl_event] %s start:%d len:%d text:%s windowID:%d",
						(*element).second,
						e.edit.start,e.edit.length,
						e.edit.text,
						e.edit.windowID
					);

					break;
				}

				if (t == SDL_EVENT_TEXT_EDITING_CANDIDATES){
					if(e.edit_candidates.candidates == nullptr)break;

					int count = 0;
					while(count < e.edit_candidates.num_candidates){
						Log("[log_sdl_event] %s candidates:%s num:%d select:%d windowID:%d (%s)",
							(*element).second,
							e.edit_candidates.candidates[count],
							count,
							e.edit_candidates.selected_candidate,
							e.edit_candidates.windowID,
							e.edit_candidates.horizontal?"horizontal":"vertical"
						);
					}

					break;
				}
				
				if (t == SDL_EVENT_TEXT_INPUT){
					Log("[log_sdl_event] %s text:%s windowID:%d",
						(*element).second,
						e.text.text,
						e.text.windowID
					);

					break;
				}

				if (t == SDL_EVENT_MOUSE_ADDED || t == SDL_EVENT_MOUSE_REMOVED){
					Log("[log_sdl_event] %s mouseID:%d",
						(*element).second,
						e.mdevice.which
					);

					break;
				}

				if (t == SDL_EVENT_MOUSE_MOTION ){
					Log("[log_sdl_event]%s %s\tx:%f,y:%f xrel:%f,yrel:%f mouseID:%d,windowID:%d",
						(*element).second,
						get_name_sdl_mouse_button_flags(e.motion.state),
						e.motion.x,e.motion.y,
						e.motion.xrel,e.motion.yrel,
						e.motion.which,e.motion.windowID
					);
					
					break;
				}

				if (t == SDL_EVENT_MOUSE_BUTTON_DOWN || t == SDL_EVENT_MOUSE_BUTTON_UP){

					Log("[log_sdl_event]%s %s\tx:%f,y:%f clicks:%d down:%d mouseID:%d,windowID:%d",
						(*element).second,
						get_name_sdl_mouse_button_flags(e.button.button),
						e.button.x,e.button.y,
						e.button.clicks,e.button.down,
						e.button.which,e.button.windowID
					);

					break;
				}

				if (t == SDL_EVENT_MOUSE_WHEEL){

					Log(
						"[log_sdl_event]%s direction:%d x:%f,y:%f " //connect to
						"mouse_x:%f,mouse_y:%f int_x:%d,int_y:%d mouseID:%d,windowID:%d",
						(*element).second,
						e.wheel.direction,
						e.wheel.x,e.wheel.y,
						e.wheel.mouse_x,e.wheel.mouse_y,
						e.wheel.integer_x,e.wheel.integer_y,
						e.wheel.which,e.wheel.windowID
					);
					
					break;
				}

				if (t == SDL_EVENT_JOYSTICK_ADDED
				 || t == SDL_EVENT_JOYSTICK_REMOVED
				 || t == SDL_EVENT_JOYSTICK_UPDATE_COMPLETE){
					Log("[log_sdl_event] %s joystickID:%d",(*element).second,e.jdevice.which);
					break;
				}

				if (t == SDL_EVENT_JOYSTICK_AXIS_MOTION){
					Log("[log_sdl_event] %s axis:%d value:%d joystickID:%d",
						(*element).second,
						e.jaxis.axis,e.jaxis.value,
						e.jaxis.which);
					
					break;
				}

				if (t == SDL_EVENT_JOYSTICK_BALL_MOTION){
					Log(
						"[log_sdl_event]%s ball:%d xrel:%d,yrel:%d joystickID:%d",
						(*element).second,
						e.jball.ball,
						e.jball.xrel,e.jball.yrel,
						e.jball.which
					);

					break;
				}

				if (t == SDL_EVENT_JOYSTICK_HAT_MOTION){
					Log("[log_sdl_event]%s hat:%d value:%d joystickID:%d",
						(*element).second,
						e.jhat.hat,e.jhat.value,
						e.jhat.which
					);

					break;
				}

				if (t == SDL_EVENT_JOYSTICK_BUTTON_DOWN || t == SDL_EVENT_JOYSTICK_BUTTON_UP){
					Log("[log_sdl_event]%s button:%d down:%d joystickID:%d",
						(*element).second,
						e.jbutton.button,e.button.down,
						e.jbutton.which
					);

					break;
				}

				if (t == SDL_EVENT_JOYSTICK_BATTERY_UPDATED){
					Log("[log_sdl_event]%s state:%s percent:%d joystickID:%d",
						(*element).second,
						get_name_sdl_power_state(e.jbattery.state),
						e.jbattery.percent,
						e.jbattery.which
					);

					break;
				}

				if (t == SDL_EVENT_GAMEPAD_ADDED
				 || t == SDL_EVENT_GAMEPAD_REMOVED
				 || t == SDL_EVENT_GAMEPAD_REMAPPED
				 || t == SDL_EVENT_GAMEPAD_UPDATE_COMPLETE
				 || t == SDL_EVENT_GAMEPAD_STEAM_HANDLE_UPDATED){
					Log("[log_sdl_event] %s joystickID:%d",
						(*element).second,e.gdevice.which);

					break;
				}

				if (t == SDL_EVENT_GAMEPAD_AXIS_MOTION){
					Log("[log_sdl_event] %s axis:%d value:%d joystickID:%d",
						(*element).second,
						e.gaxis.axis,e.gaxis.value,
						e.gaxis.which);
					
					break;
				}

				if (t == SDL_EVENT_GAMEPAD_BUTTON_DOWN || t == SDL_EVENT_GAMEPAD_BUTTON_UP){
					Log("[log_sdl_event]%s button:%d down:%d joystickID:%d",
						(*element).second,
						e.gbutton.button,e.gbutton.down,
						e.gbutton.which
					);

					break;
				}

				if (t == SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN
				 || t == SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION
				 || t == SDL_EVENT_GAMEPAD_TOUCHPAD_UP){

					Log("[log_sdl_event]%s touchpad:%d finger:%d x:%f,y:%f pressure:%f joystickID:%d",
						(*element).second,
						e.gtouchpad.touchpad,e.gtouchpad.finger,
						e.gtouchpad.x,e.gtouchpad.y,
						e.gtouchpad.pressure,
						e.gtouchpad.which
					);

					break;
				}

				if (t == SDL_EVENT_GAMEPAD_SENSOR_UPDATE ){
					Log("[log_sdl_event] %s sensor:%d data:%f,%f,%f joystickID:%d",
						(*element).second,
						e.gsensor.sensor,
						e.gsensor.data[0],
						e.gsensor.data[1],
						e.gsensor.data[2],
						e.gsensor.which
					);
				}

				if (t == SDL_EVENT_AUDIO_DEVICE_ADDED
				 || t == SDL_EVENT_AUDIO_DEVICE_REMOVED
				 || t == SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED){

					Log("[log_sdl_event] %s recording:%d AudioDeviceID:%d",
					(*element).second,
					e.adevice.recording,
					e.adevice.which);

					break;
				}

				if (t == SDL_EVENT_CAMERA_DEVICE_ADDED
				 || t == SDL_EVENT_CAMERA_DEVICE_REMOVED
				 || t == SDL_EVENT_CAMERA_DEVICE_APPROVED
				 || t == SDL_EVENT_CAMERA_DEVICE_DENIED){

					Log("[log_sdl_event] %s CameraID:%d",
					(*element).second,
					e.cdevice.which);

					break;
				}

				if (t == SDL_EVENT_SENSOR_UPDATE){
					Log("[log_sdl_event] %s data:%f,%f,%f,%f,%f,%f SensorID:%d",
						(*element).second,
						e.sensor.data[0],
						e.sensor.data[1],
						e.sensor.data[2],
						e.sensor.data[3],
						e.sensor.data[4],
						e.sensor.data[5],
						e.sensor.which);

					break;
				}

				if (t >= SDL_EVENT_USER && t <= SDL_EVENT_LAST){
					Log("[log_sdl_event] %s windowID:%d code:%d",
						(*element).second,
						e.user.windowID,
						e.user.code
					);
					break;
				}

				if(t == SDL_EVENT_FINGER_DOWN
				 ||t == SDL_EVENT_FINGER_UP
				 ||t == SDL_EVENT_FINGER_MOTION
				 ||t == SDL_EVENT_FINGER_CANCELED){

					Log("[log_sdl_event] %s touchID:%ld fingerID:%ld "//connect to
						"x:%f,y:%f dx:%f,dy:%f pressure:%f windowID:%d",
						(*element).second,
						e.tfinger.touchID,
						e.tfinger.fingerID,
						e.tfinger.x,e.tfinger.y,
						e.tfinger.dx,e.tfinger.dy,
						e.tfinger.pressure,
						e.tfinger.windowID
					);

					break;
				}

				if (t == SDL_EVENT_PINCH_BEGIN
				 || t == ::SDL_EVENT_PINCH_UPDATE
				 || t == ::SDL_EVENT_PINCH_END){
					Log("[log_sdl_event] %s scale:%f windowID:%d",
						(*element).second,
						e.pinch.scale,
						e.pinch.windowID);

					break;
				}

				if (t == SDL_EVENT_PEN_PROXIMITY_IN
				 || t == SDL_EVENT_PEN_PROXIMITY_OUT){
					Log("[log_sdl_event] %s penID:%d windowID:%d",
						(*element).second,
						e.pproximity.which,
						e.pproximity.windowID);

					break;
				}

				if (t == SDL_EVENT_PEN_DOWN || t == SDL_EVENT_PEN_UP){

					Log("[log_sdl_event] %s pen_state:%s x:%f,y:%f eraser:%d down:%d penID:%d windowID:%d",
						(*element).second,
						get_name_sdl_pen_input_flags(e.ptouch.pen_state),
						e.ptouch.x,e.ptouch.y,
						e.ptouch.eraser,e.ptouch.down,
						e.ptouch.which,
						e.ptouch.windowID);

					break;
				}

				if (t == SDL_EVENT_PEN_MOTION){

					Log("[log_sdl_event] %s pen_state:%s x:%f,y:%f penID:%d windowID:%d",
						(*element).second,
						get_name_sdl_pen_input_flags(e.pmotion.pen_state),
						e.pmotion.x,e.pmotion.y,
						e.pmotion.which,
						e.pmotion.windowID);

					break;
				}

				if (t == SDL_EVENT_PEN_BUTTON_DOWN
				 || t == SDL_EVENT_PEN_BUTTON_UP){

					Log("[log_sdl_event] %s pen_state:%s x:%f,y:%f button:%d down:%d penID:%d windowID:%d",
						(*element).second,
						get_name_sdl_pen_input_flags(e.pbutton.pen_state),
						e.pbutton.x,e.pbutton.y,
						e.pbutton.button,e.pbutton.down,
						e.pbutton.which,
						e.pbutton.windowID);

					break;
				}

				if (t == SDL_EVENT_PEN_AXIS){
					
					Log("[log_sdl_event] %s pen_state:%s x:%f,y:%f axis:%s value:%f penID:%d windowID:%d",
						(*element).second,
						get_name_sdl_pen_input_flags(e.paxis.pen_state),
						e.paxis.x,e.paxis.y,
						get_name_sdl_pen_axis(e.paxis.axis),e.paxis.value,
						e.paxis.which,
						e.paxis.windowID);

					break;
				}

				if (t == SDL_EVENT_RENDER_TARGETS_RESET
				 || t == SDL_EVENT_RENDER_DEVICE_RESET
				 || t == SDL_EVENT_RENDER_DEVICE_LOST){

					Log("[log_sdl_event] %s windowID:%d",
						(*element).second,e.render.windowID);

					break;
				}

				if (t == SDL_EVENT_DROP_BEGIN
				 || t == SDL_EVENT_DROP_FILE
				 || t == SDL_EVENT_DROP_TEXT
				 || t == SDL_EVENT_DROP_COMPLETE
				 || t == SDL_EVENT_DROP_POSITION){
					Log("[log_sdl_event] %s x:%f,y:%f source:%s data:%s windowID:%d",
						(*element).second,
						e.drop.x,e.drop.y,
						e.drop.source,e.drop.data,
						e.drop.windowID);

					break;
				}

				if (t == SDL_EVENT_CLIPBOARD_UPDATE){
					if (e.clipboard.mime_types == nullptr) break;
					
					for(int count=0;count < e.clipboard.num_mime_types;count++){
						Log("[log_sdl_event] %s owner:%d mime_types:%s",
							(*element).second,
							e.clipboard.owner,
							e.clipboard.mime_types[count]);
					}

					break;
				}

				Log("[log_sdl_event] %s",(*element).second);

			}while(false);

		}else{
			Log("[log_sdl_event] (missing) %d",e.type);
		}

	}

	//provided by SDL, GetEventDescription
	template <typename LogT>
	void log_sdl_event_description(const SDL_Event &e, LogT &&Log = SDL_Log) noexcept{
		std::string buffer{};
		size_t size_need = SDL_GetEventDescription(&e,nullptr,0);
		buffer.resize(size_need+1);
		SDL_GetEventDescription(&e,buffer.data(),size_need);

		Log("[log_sdl_event_description] %s",buffer.c_str());
	}

	template<typename LogT>
	void log_sdl_mouse(LogT &&Log){
		if (!SDL_HasMouse())return;

		int count = 0;
		SDL_MouseID* m_ids = SDL_GetMice(&count);

		if (m_ids != nullptr){
			for (int i = 0;i < count; i++){
				Log("[log_sdl_mouse] %s",SDL_GetMouseNameForID(m_ids[i]));
			}
		}

		SDL_free(m_ids);
	}

	template<typename LogT>
	void log_sdl_mouse_state(LogT &&Log){
		if (!SDL_HasMouse())return;

		float x=0,y=0;
		float rx=0,ry=0;
		float gx=0,gy=0;
		SDL_MouseButtonFlags f=0,rf=0,gf=0;

		f = SDL_GetMouseState(&x,&y);
		rf = SDL_GetRelativeMouseState(&rx,&ry);
		gf = SDL_GetGlobalMouseState(&gx,&gy);

		Log("[log_sdl_mouse_state] f:%s x:%f,y:%f rf:%s rx:%f,ry:%f gf:%s gx:%f,gy:%f",
			core::get_name_sdl_mouse_button_flags(f),x,y,
			core::get_name_sdl_mouse_button_flags(rf),rx,ry,
			core::get_name_sdl_mouse_button_flags(gf),gx,gy
		);

	}

	template <typename LogT>
	void log_sdl_power_info(LogT &&Log = SDL_Log){
		int seconds{},percent{};
		SDL_PowerState s = SDL_GetPowerInfo(&seconds,&percent);
		Log("power(state:%s,left seconds:%ds,percent:%d%%)",
			get_name_sdl_power_state(s),seconds,percent);
	}

/*
	SDL的类型有的对应的Get[ObjectType]Proerty去获取a group of properties
	也可以SDL_CreateProperties创建或去用SDL_GetGlobalProperties获取全局的组
	创建来的props组，需要SDL_DestroyProperties
	SDL_LockProperties,SDL_UnlockProperties以保证安全读写

	可以在group中SDL_Set[Type]Property设置一个name为某个Type的值
	可以在group中SDL_Get[Type]Property获取一个name为某个Type的值
*/
	inline const char* toname_sdl_property_type(SDL_PropertyType t) noexcept{
		std::unordered_map<SDL_PropertyType, const char*> v = {
			{SDL_PROPERTY_TYPE_INVALID,"SDL_PROPERTY_TYPE_INVALID"},
			{SDL_PROPERTY_TYPE_POINTER,"SDL_PROPERTY_TYPE_POINTER"},
			{SDL_PROPERTY_TYPE_STRING,"SDL_PROPERTY_TYPE_STRING"},
			{SDL_PROPERTY_TYPE_NUMBER,"SDL_PROPERTY_TYPE_NUMBER"},
			{SDL_PROPERTY_TYPE_FLOAT,"SDL_PROPERTY_TYPE_FLOAT"},
			{SDL_PROPERTY_TYPE_BOOLEAN,"SDL_PROPERTY_TYPE_BOOLEAN"}

		};

		if (v.find(t) != v.end()){
			return v[t];
		}else{
			return nullptr;
		}

	}

	template <typename LogT>
	void log_sdl_property(SDL_PropertiesID props, const char *name,  LogT &&Log = SDL_Log){
		SDL_PropertyType type = SDL_GetPropertyType(props,name);

		switch(type){
			case SDL_PROPERTY_TYPE_INVALID:
				Log("[log_sdl_property] name:%s\n%s",name,toname_sdl_property_type(type));
				break;

			case SDL_PROPERTY_TYPE_POINTER:
				Log("[log_sdl_property] name:%s\n%s",name,toname_sdl_property_type(type));
				break;

			case SDL_PROPERTY_TYPE_STRING:
				Log("[log_sdl_property] name:%s\n%s:%s",name,
					toname_sdl_property_type(type),
					SDL_GetStringProperty(props,name,""));
				break;

			case SDL_PROPERTY_TYPE_NUMBER:
				Log("[log_sdl_property] name:%s\n%s:%ld",name,
					toname_sdl_property_type(type),
					SDL_GetNumberProperty(props,name,0));
				break;

			case SDL_PROPERTY_TYPE_FLOAT:
				Log("[log_sdl_property] name:%s\n%s:%f",name,
					toname_sdl_property_type(type),
					SDL_GetFloatProperty(props,name,0.0f));
				break;

			case SDL_PROPERTY_TYPE_BOOLEAN:
				Log("[log_sdl_property] name:%s\n%s:%d",name,
					toname_sdl_property_type(type),
					SDL_GetBooleanProperty(props,name,false));
				break;
			default:
				Log("[log_sdl_property] unknown type:%x",type);
				break;
		}

	}

	template <typename LogT>
	void log_sdl_properties(SDL_PropertiesID props, LogT &&Log = SDL_Log){
		SDL_EnumerateProperties(props,
			[&Log](void *userdata, SDL_PropertiesID props, const char *name) -> void{
				log_sdl_property(props, name, Log);
			}, nullptr);
	}

	template <typename LogT>
	void log_sdl_render_drivers(LogT &&Log = SDL_Log){
		int num = SDL_GetNumRenderDrivers();
		
		for (int i=0; i < num ; i++){
			Log("%s",SDL_GetRenderDriver(i));
		}
	}

	template <typename LogT>
	void log_sdl_version(LogT &&Log = SDL_Log){
		Log("[log_sdl_version] SDL Version:%d",SDL_GetVersion());
		Log("[log_sdl_version] SDL Revision:%s",SDL_GetRevision());
	}

}

#endif
